apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounting-service
  template:
    metadata:
      labels:
        app: accounting-service
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
        - name: accounting-service
          image: localhost:32000/accounting-service:01
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "postgres-service2"
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: "accounting"
            - name: DB_USERNAME
              value: "user"
            - name: DB_PASSWORD
              value: "postgres"
