apiVersion: v1
kind: Service
metadata:
  name: accounting-service
  labels:
    app: accounting-service
spec:
  type: ClusterIP
  selector:
    app: accounting-service
  ports:
    - port: 8080
      name: "8080"
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: accounting-service-external
  labels:
    app: accounting-service
spec:
  type: NodePort
  selector:
    app: accounting-service
  ports:
    - port: 8080
      name: accounting-service
